const allCountries = [
  { code: "AFG", name: "Afghanistan" },
  { code: "ALB", name: "Albania" },
  { code: "ALG", name: "Algeria" },
  { code: "ASA", name: "American Samoa" },
  { code: "AND", name: "Andorra" },
  { code: "ANG", name: "Angola" },
  { code: "ANT", name: "Antigua" },
  { code: "ARG", name: "Argentina" },
  { code: "ARM", name: "Armenia" },
  { code: "ARU", name: "Aruba" },
  { code: "AUS", name: "Australia" },
  { code: "AUT", name: "Austria" },
  { code: "AZE", name: "Azerbaijan" },
  { code: "BAH", name: "Bahamas" },
  { code: "BRN", name: "Bahrain" },
  { code: "BAN", name: "Bangladesh" },
  { code: "BAR", name: "Barbados" },
  { code: "BLR", name: "Belarus" },
  { code: "BEL", name: "Belgium" },
  { code: "BLZ", name: "Belize" },
  { code: "BEN", name: "Benin" },
  { code: "BER", name: "Bermuda" },
  { code: "BHU", name: "Bhutan" },
  { code: "BOL", name: "Bolivia" },
  { code: "BIH", name: "Bosnia-Herzegovina" },
  { code: "BOT", name: "Botswana" },
  { code: "BRA", name: "Brazil" },
  { code: "IVB", name: "British Virgin Islands" },
  { code: "BRU", name: "Brunei" },
  { code: "BUL", name: "Bulgaria" },
  { code: "BUR", name: "Burkina Faso" },
  { code: "BDI", name: "Burundi" },
  { code: "CAM", name: "Cambodia" },
  { code: "CMR", name: "Cameroon" },
  { code: "CAN", name: "Canada" },
  { code: "CPV", name: "Cape Verde Islands" },
  { code: "CAY", name: "Cayman Islands" },
  { code: "CAF", name: "Central African Republic" },
  { code: "CHA", name: "Chad" },
  { code: "CHI", name: "Chile" },
  { code: "CHN", name: "China" },
  { code: "TPE", name: "Chinese Taipei" },
  { code: "COL", name: "Colombia" },
  { code: "COM", name: "Comoros" },
  { code: "COD", name: "Congo, Dem. Rep. (Zaire)" },
  { code: "COK", name: "Cook Islands" },
  { code: "CRC", name: "Costa Rica" },
  { code: "CRO", name: "Croatia" },
  { code: "CUB", name: "Cuba" },
  { code: "CUW", name: "Curacao" },
  { code: "CYP", name: "Cyprus" },
  { code: "CZE", name: "Czechia" },
  { code: "YMD", name: "Democratic Rep. of Yemen" },
  { code: "DEN", name: "Denmark" },
  { code: "DJI", name: "Djibouti" },
  { code: "DMA", name: "Dominica" },
  { code: "DOM", name: "Dominican Republic" },
  { code: "ECU", name: "Ecuador" },
  { code: "EGY", name: "Egypt" },
  { code: "ESA", name: "El Salvador" },
  { code: "GEQ", name: "Equatorial Guinea" },
  { code: "ERI", name: "Eritrea" },
  { code: "EST", name: "Estonia" },
  { code: "ETH", name: "Ethiopia" },
  { code: "FIJ", name: "Fiji" },
  { code: "FIN", name: "Finland" },
  { code: "FRA", name: "France" },
  { code: "GAB", name: "Gabon" },
  { code: "GAM", name: "Gambia" },
  { code: "GEO", name: "Georgia" },
  { code: "GER", name: "Germany" },
  { code: "GHA", name: "Ghana" },
  { code: "GBR", name: "Great Britain" },
  { code: "GRE", name: "Greece" },
  { code: "GRN", name: "Grenada" },
  { code: "GUD", name: "Guadeloupe" },
  { code: "GUM", name: "Guam" },
  { code: "GUA", name: "Guatemala" },
  { code: "GUI", name: "Guinea" },
  { code: "GUY", name: "Guyana" },
  { code: "HAI", name: "Haiti" },
  { code: "HON", name: "Honduras" },
  { code: "HKG", name: "Hong Kong" },
  { code: "HUN", name: "Hungary" },
  { code: "ISL", name: "Iceland" },
  { code: "IND", name: "India" },
  { code: "INA", name: "Indonesia" },
  { code: "IRI", name: "Iran" },
  { code: "IRQ", name: "Iraq" },
  { code: "IRL", name: "Ireland" },
  { code: "ISR", name: "Israel" },
  { code: "ITA", name: "Italy" },
  { code: "CIV", name: "Ivory Coast" },
  { code: "JAM", name: "Jamaica" },
  { code: "JPN", name: "Japan" },
  { code: "JOR", name: "Jordan" },
  { code: "KAZ", name: "Kazakhstan" },
  { code: "KEN", name: "Kenya" },
  { code: "KIR", name: "Kiribati" },
  { code: "KUW", name: "Kuwait" },
  { code: "KGZ", name: "Kyrgyzstan" },
  { code: "LAO", name: "Laos" },
  { code: "LAT", name: "Latvia" },
  { code: "LBN", name: "Lebanon" },
  { code: "LES", name: "Lesotho" },
  { code: "LBR", name: "Liberia" },
  { code: "LBA", name: "Libya" },
  { code: "LIE", name: "Liechtenstein" },
  { code: "LTU", name: "Lithuania" },
  { code: "LUX", name: "Luxembourg" },
  { code: "NOR", name: "Norway" },
  { code: "OMA", name: "Oman" },
  { code: "PAK", name: "Pakistan" },
  { code: "POL", name: "Poland" },
  { code: "POR", name: "Portugal" },
  { code: "QAT", name: "Qatar" },
  { code: "ROU", name: "Romania" },
  { code: "RUS", name: "Russia" },
  { code: "ESP", name: "Spain" },
  { code: "SWE", name: "Sweden" },
  { code: "SUI", name: "Switzerland" },
  { code: "TUR", name: "Turkiye" },
  { code: "USA", name: "United States" },
  { code: "ZIM", name: "Zimbabwe" },
];

const mainCountries = [
  { code: "all", name: "All" },
  { code: "FRA", name: "France", flagCode: "FR" },
  { code: "USA", name: "United States", flagCode: "US" },
  { code: "ESP", name: "Spain", flagCode: "ES" },
  { code: "GBR", name: "United Kingdom", flagCode: "GB" },
  { code: "GER", name: "Germany", flagCode: "DE" },
  { code: "ITA", name: "Italy", flagCode: "IT" },
  { code: "ARG", name: "Argentina", flagCode: "AR" },
  { code: "AUS", name: "Australia", flagCode: "AU" },
  { code: "AUT", name: "Austria", flagCode: "AT" },
  { code: "BEL", name: "Belgium", flagCode: "BE" },
  { code: "BRA", name: "Brazil", flagCode: "BR" },
  { code: "CAN", name: "Canada", flagCode: "CA" },
  { code: "CHI", name: "Chile", flagCode: "CL" },
  { code: "SRB", name: "Serbia", flagCode: "RS" },
  { code: "CRO", name: "Croatia", flagCode: "HR" },
  { code: "CZE", name: "Czech Republic", flagCode: "CZ" },
  { code: "DEN", name: "Denmark", flagCode: "DK" },
  { code: "ECU", name: "Ecuador", flagCode: "EC" },
  { code: "EST", name: "Estonia", flagCode: "EE" },
  { code: "FIN", name: "Finland", flagCode: "FI" },
  { code: "GRE", name: "Greece", flagCode: "GR" },
  { code: "HUN", name: "Hungary", flagCode: "HU" },
  { code: "IRL", name: "Ireland", flagCode: "IE" },
  { code: "JPN", name: "Japan", flagCode: "JP" },
  { code: "RUS", name: "Russia", flagCode: "RU" },
];

export const countries: { code: string; name: string; flagCode?: string }[] = [
  ...mainCountries,
  ...allCountries.filter(
    (country) => !mainCountries.some((main) => main.code === country.code)
  ),
];

export const isoToEmoji = (countryCode: string) =>
  countryCode
    .slice(0, 2) // keep the first two letters
    .split("")
    .map((letter) => (letter.charCodeAt(0) % 32) + 0x1f1e5)
    .map((emojiCode) => String.fromCodePoint(emojiCode))
    .join("");
